# group_vars/all/exclusions.yml
excluded_users:
  - root
  - admin
  - tux
  - proactiva
  - iacolcoauto
  - ansible_test
  - halt
  - shutdown
  - sync
  - nfsnobody
  - oracle
  - postgres
  - pos
  - alktstwms
  - alktstems

# Regex listo para usar con grep/awk (escapa caracteres especiales)
excluded_users_regex: "{{ excluded_users | map('regex_escape') | join('|') }}"
